import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
export const fixturesDir = resolve(here, '..', 'fixtures');
export const moveV1Dir = resolve(fixturesDir, 'move', 'v1');
export const moveV2Dir = resolve(fixturesDir, 'move', 'v2');
export const noopScriptDir = resolve(fixturesDir, 'scripts');
export const noopScriptPath = resolve(noopScriptDir, 'scripts', 'noop.move');
// Move package name declared in `fixtures/scripts/Move.toml` — the
// `movement move compile` build output lands under `build/<name>/`,
// so consumers locating the produced `.mv` need this constant.
export const noopScriptPackageName = 'movehat_integration_scripts';
// Resolved path to the compiled script bytecode AFTER `movement move
// compile` has been run from `noopScriptDir`. Not a committed artifact —
// regenerated by the integration test's `beforeAll` step. The Movement
// CLI's `move run-script --script-path` path fails to resolve the
// `AptosFramework` dep on this version of the CLI (uses
// `aptos-move/framework` instead of `aptos-move/framework/aptos-
// framework`), so the integration test compiles + submits via the
// `--compiled-script-path` branch instead. When the upstream
// `run-script --script-path` issue lands a fix, this helper and the
// `compileNoopScript` call below can both retire.
export const compiledNoopPath = resolve(
  noopScriptDir,
  'build',
  noopScriptPackageName,
  'bytecode_scripts',
  'main.mv',
);
